### ISSUE TITLE
Up side down result

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [UESTC-Ingress/IFSolver#1]
Tried on our IFS puzzle, works really well except we figured out the output(result_full.png) is up side down. 

Can anyone reproduce this problem?

**Comment by YukariChiba** [comment]
Yes. Actually I noticed that the demo image in `README.md` is also up side down.

I'll fix it soon&trade;.

**Comment by YukariChiba** [comment]
I confused the relationship between opencv's xy coordinates and portal's latitude and longitude.

Now the result should be normal now.
