### ISSUE TITLE
Cannot open 「split image」 window on MacOS Big Sur

### ISSUE THREAD

**Issue by BillSJC** [UESTC-Ingress/IFSolver#18]
It just shown nothing after print 「[IFSolver] Splitting Images」
MacOS 11.0.1
python 3.7.6

**Comment by YukariChiba** [comment]
I don't have any device running Mac OS.
So...
¯\_(ツ)_/¯

**Comment by MualaniMarine** [comment]
> It just shown nothing after print 「[IFSolver] Splitting Images」
> MacOS 11.0.1
> python 3.7.6

try python 3.9.1

**Comment by YukariChiba** [comment]
The old version is now deprecated. Please try the latest version in `master` branch.
